Fixes and improvements related to Linux Kernel header mounts on other Linux distros
nestybox/sysbox-mgr pull request #24
Opened 2021-04-06 00:47 UTC by joanbm

Those are various improvements related to Linux Kernel header mounts on other Linux distros, specially getting sysbox to work on Arch:

* Commit 1: "Fix: longestCommonPath should not truncate a path component"

This is just a fix for a very very low impact issue I found while manually testing various scenarios for Linux Kernel header mounts, as far as I know it does not have any impact on any supported configuration, but it's better to leave it fixed to avoid future issues with other distros.

* Commit 2: Create intermediate paths when symlinking Linux kernel headers

This fixes an issue launching containers which only happens on very obscure scenarios on supported/typical configurations, but which happens on Arch (after merging "Add Linux Kernel header path for Arch Linux" from sysbox-libs) when launching Alpine-based containers.

* Commit 3: Don't fail launching the containers on host kernel headers not found

This is a functional change to facilitate people getting basic Sysbox functionality to work on other distributions, if the kernel headers on the host can not be found, it is a warning instead of an error which prevents launching the containers.

I ran the test-mgr tests and they all passed.

2021-04-06 20:52 UTC, rodnymolina requested changes
Excellent job @joanbm! Thank you very much!

Have just a couple of very minor comments.

2021-04-06 20:52 UTC, rodnymolina commented on mgr.go
> +	var fsEntries []configs.FsEntry
Can you please move this "Create kernel-header softlink" comment further below where the corresponding code is being executed, and add a new comment here describing what we're doing? Something like ...

"In certain distros, such as 'alpine', the typical "/usr/src" kernel path may not exist, so create an associated fsEntry to ensure that the kernel softlink addition (below) can be properly carried out."

2021-04-06 20:52 UTC, rodnymolina commented on utils.go
> +		logrus.Warnf("host linux headers not found at %s, will not be mounted inside the container", kernelHdrPath)
This message will be generated only once during sysbox-mgr initialization, so what about re-phrasing it like this?

"No kernel-headers found in host file-system at %s. No headers will be mounted inside any of the containers."

2021-04-07 17:24 UTC, joanbm commented
I agree, the code and messages are more readable with the changes you comment. Changed and changed.

2021-04-07 17:28 UTC, rodnymolina approved these changes
Awesome!

2021-04-07 17:28 UTC, merged